import React from 'react';

/**
 * Top application navigation header.
 * @param {{
 *   currentTab: string,
 *   setCurrentTab: (tab: string) => void,
 *   isMockMode?: boolean,
 *   isFixtureMode?: boolean
 * }} props
 */
export function Header({ currentTab, setCurrentTab, isMockMode = false, isFixtureMode = false }) {
  return (
    <header className="app-header">
      <div className="header-brand">
        <div className="brand-logo">
          <span className="logo-symbol">&lt;/&gt;</span>
        </div>
        <div className="brand-text">
          <h1 className="brand-title">AI Programming Error Helper</h1>
          <p className="brand-tagline">Deterministic Static Analysis &bull; AI-Assisted Educational Explanations</p>
        </div>
      </div>

      <div className="header-center">
        {isMockMode && (
          <span className="mock-badge" title="AI responses are generated by deterministic local mock provider">
            <span className="pulse-dot"></span>
            MOCK MODE
          </span>
        )}
        {isFixtureMode && (
          <span className="fixture-badge" title="Running in B-M1 Fixture Mode without backend requirement">
            FIXTURE MODE (B-M1)
          </span>
        )}
      </div>

      <nav className="header-nav" aria-label="Main Navigation">
        <button
          type="button"
          className={`nav-link ${currentTab === 'analyze' ? 'active' : ''}`}
          onClick={() => setCurrentTab('analyze')}
          aria-current={currentTab === 'analyze' ? 'page' : undefined}
        >
          🔍 Analyze
        </button>
        <button
          type="button"
          className={`nav-link ${currentTab === 'history' ? 'active' : ''}`}
          onClick={() => setCurrentTab('history')}
          aria-current={currentTab === 'history' ? 'page' : undefined}
        >
          📜 History
        </button>
        <button
          type="button"
          className={`nav-link ${currentTab === 'analytics' ? 'active' : ''}`}
          onClick={() => setCurrentTab('analytics')}
          aria-current={currentTab === 'analytics' ? 'page' : undefined}
        >
          📊 Analytics
        </button>
      </nav>
    </header>
  );
}
